---
- id: 1
  day: Sábado 14
  start_time:
  end_time:
  duration:
  activity: Recepción de Diócesis
- id: 2
  day: Sábado 14
  start_time:
  end_time:
  duration:
  activity: Entrega de Kits
- id: 3
  day: Domingo 15
  start_time: '01:30'
  end_time: '08:00'
  duration: '6:30'
  activity: Instalación de stands
- id: 4
  day: Domingo 15
  start_time:
  end_time:
  duration:
  activity: Instalación de capilla Santísimo
- id: 5
  day: Domingo 15
  start_time: '07:00'
  end_time: '09:00'
  duration: '2:00'
  activity: Desfile por diócesis
- id: 6
  day: Domingo 15
  start_time: '09:00'
  end_time: '10:00'
  duration: '1:00'
  activity: Entrada a la Arena
- id: 7
  day: Domingo 15
  start_time: '10:00'
  end_time: '10:05'
  duration: '0:05'
  activity: Video histórico Ultreyas MTY 1998-2026
- id: 8
  day: Domingo 15
  start_time: '10:05'
  end_time: '10:20'
  duration: '0:15'
  activity: Grupo Folclórico
- id: 9
  day: Domingo 15
  start_time: '10:20'
  end_time: '10:50'
  duration: '0:30'
  activity: Presentación Maestros de Ceremonia y Autoridades
- id: 10
  day: Domingo 15
  start_time: '10:50'
  end_time: '10:55'
  duration: '0:05'
  activity: Palabras de bienvenida - Presidente Nacional
- id: 11
  day: Domingo 15
  start_time: '10:55'
  end_time: '11:00'
  duration: '0:05'
  activity: Palabras de bienvenida - Presidente Diocesano
- id: 12
  day: Domingo 15
  start_time: '11:00'
  end_time: '11:05'
  duration: '0:05'
  activity: Palabras de bienvenida
- id: 13
  day: Domingo 15
  start_time: '10:50'
  end_time: '11:50'
  duration: '1:00'
  activity: Presentación del Santísimo y Entronización Virgen del Roble
- id: 14
  day: Domingo 15
  start_time: '11:50'
  end_time: '12:00'
  duration: '0:10'
  activity: Canto de Colores
- id: 15
  day: Domingo 15
  start_time: '12:00'
  end_time: '12:45'
  duration: '0:45'
  activity: Tema 1
- id: 16
  day: Domingo 15
  start_time: '12:45'
  end_time: '12:50'
  duration: '0:05'
  activity: Agradecimiento Tema 1
- id: 17
  day: Domingo 15
  start_time: '12:45'
  end_time: '14:05'
  duration: '1:20'
  activity: Comida y descanso
- id: 18
  day: Domingo 15
  start_time: '14:05'
  end_time: '14:15'
  duration: '0:10'
  activity: Video MCC Monterrey
- id: 19
  day: Domingo 15
  start_time: '14:05'
  end_time: '15:50'
  duration: '1:45'
  activity: Eucaristía
- id: 20
  day: Domingo 15
  start_time: '15:50'
  end_time: '16:15'
  duration: '0:25'
  activity: Vivencia 1
- id: 21
  day: Domingo 15
  start_time: '16:15'
  end_time: '16:20'
  duration: '0:05'
  activity: Agradecimiento Vivencia 1
- id: 22
  day: Domingo 15
  start_time: '16:15'
  end_time: '16:40'
  duration: '0:25'
  activity: Animación
- id: 23
  day: Domingo 15
  start_time: '16:40'
  end_time: '17:05'
  duration: '0:25'
  activity: Vivencia 2
- id: 24
  day: Domingo 15
  start_time: '17:05'
  end_time: '17:10'
  duration: '0:05'
  activity: Agradecimiento Vivencia 2
- id: 25
  day: Domingo 15
  start_time: '17:05'
  end_time: '17:15'
  duration: '0:10'
  activity: Video MCC Monterrey
- id: 26
  day: Domingo 15
  start_time: '17:15'
  end_time: '18:00'
  duration: '0:45'
  activity: Tema 2
- id: 27
  day: Domingo 15
  start_time: '18:00'
  end_time: '18:05'
  duration: '0:05'
  activity: Agradecimiento Tema 2
- id: 28
  day: Domingo 15
  start_time: '18:00'
  end_time: '18:20'
  duration: '0:20'
  activity: Animación
- id: 29
  day: Domingo 15
  start_time: '18:20'
  end_time: '18:45'
  duration: '0:25'
  activity: Vivencia 3
- id: 30
  day: Domingo 15
  start_time: '18:45'
  end_time: '18:50'
  duration: '0:05'
  activity: Agradecimiento Vivencia 3
- id: 31
  day: Domingo 15
  start_time: '18:45'
  end_time: '19:00'
  duration: '0:15'
  activity: Indicaciones y cierre del día
- id: 32
  day: Domingo 15
  start_time: '19:00'
  end_time:
  duration:
  activity: Regreso a las parroquias y lugar de hospedaje
- id: 33
  day: Lunes 16
  start_time: '08:00'
  end_time: '08:30'
  duration: '0:30'
  activity: Llegada y música instrumental
- id: 34
  day: Lunes 16
  start_time: '08:30'
  end_time: '08:50'
  duration: '0:20'
  activity: Oraciones de la mañana
- id: 35
  day: Lunes 16
  start_time: '08:50'
  end_time: '09:45'
  duration: '0:55'
  activity: Rosario
- id: 36
  day: Lunes 16
  start_time: '09:45'
  end_time: '10:10'
  duration: '0:25'
  activity: Vivencia 4
- id: 37
  day: Lunes 16
  start_time: '10:10'
  end_time: '10:15'
  duration: '0:05'
  activity: Agradecimiento Vivencia 4
- id: 38
  day: Lunes 16
  start_time: '10:10'
  end_time: '10:55'
  duration: '0:45'
  activity: Tema 3
- id: 39
  day: Lunes 16
  start_time: '10:55'
  end_time: '11:00'
  duration: '0:05'
  activity: Agradecimiento Tema 3
- id: 40
  day: Lunes 16
  start_time: '10:55'
  end_time: '11:25'
  duration: '0:30'
  activity: Intercambio y cantos
- id: 41
  day: Lunes 16
  start_time: '11:25'
  end_time: '11:50'
  duration: '0:25'
  activity: Vivencia 5
- id: 42
  day: Lunes 16
  start_time: '11:50'
  end_time: '11:55'
  duration: '0:05'
  activity: Agradecimiento Vivencia 5
- id: 43
  day: Lunes 16
  start_time: '11:50'
  end_time: '12:25'
  duration: '0:35'
  activity: Vivencia 6
- id: 44
  day: Lunes 16
  start_time: '12:25'
  end_time: '12:30'
  duration: '0:05'
  activity: Agradecimiento Vivencia 6
- id: 45
  day: Lunes 16
  start_time: '12:25'
  end_time: '13:00'
  duration: '0:35'
  activity: Palabras y oración por asesores eclesiásticos
- id: 46
  day: Lunes 16
  start_time: '13:00'
  end_time: '14:30'
  duration: '1:30'
  activity: Eucaristía
- id: 47
  day: Lunes 16
  start_time: '14:30'
  end_time: '14:50'
  duration: '0:20'
  activity: Agradecimientos generales y clausura
- id: 48
  day: Lunes 16
  start_time: '14:50'
  end_time: '15:00'
  duration: '0:30'
  activity: Entrega de comida y salida
- id: 49
  day: Lunes 16
  start_time: '15:00'
  end_time: '18:00'
  duration: '3:00'
  activity: Desmontaje
